####################################
#             SCREEN               #
####################################
screen_width=1600.0
screen_height=1200.0


####################################
#              VIRUS               #
####################################
# Distance to involve infection 
proximity_threshold = 10.0 
# Prob human to get infected
infection_rate = 1.0 

####################################
#             ZOMBIES              #
####################################
zombies=2 # Zombies spawning at start
zombie_speed_following=2.0 # Zombie alerted speed
zombie_speed=0.2 # Zombie speed unalerted
zombie_vision_range=200.0 # Zombie vision range

####################################
#             HUMANS               #
####################################
humans=50